language: node_js

node_js:
- 'node'
- '7'

script: npm run build

before_deploy: npm run doc && touch docs/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: docs
  email: developer@acaprojects.com
  name: ACA Doc Bot
